### ISSUE TITLE
Going back to collection browser from a movie should remember filters?

### ISSUE THREAD

**Issue by josephguillaume** [NoelDeMartin/media-kraken#36]
A minor point, documenting because it does get in the way of my UX, but I'm obviously happy to use the app without this changing.

1) I'm in the collection browser and I filter the collection (e.g. only watched later)
2) I click on a movie
3) I then go back (on Android, if it matters)
4) The collection browser has forgotten my filters

**Comment by NoelDeMartin** [comment]
Thanks for opening the suggestion. Yes, I've also noticed this and I've fallen into the habit of opening movies in a new tab to avoid this problem 😅. Which of course, is probably a lot harder in mobile. I'll look into this next time that I make some improvements to Media Kraken.

**Comment by NoelDeMartin** [comment]
Fixed in [v0.1.19](https://github.com/NoelDeMartin/media-kraken/blob/main/CHANGELOG.md#v0119---2024-12-03).

However, I realize it doesn't work if you refresh the page. But I'm not sure if that will be as straightforward to fix. In any case, that should be fixed when I eventually migrate Media Kraken to [Aerogel](https://aerogel.js.org/), which hopefully will be soon 🤞.
